apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - 00-namespace.yaml
  - 10-rbac.yaml
  - 20-deployment.yaml

generators:
  - ksops-generator.yaml
