apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.0/manifests/install.yaml
  - ingress.yaml
  - cmp-sops.yaml
  - applicationset.yaml
  - project.yaml
  - repo-ssh.secret.yaml

patches:
  # Active le mode insecure (TLS terminé par Caddy)
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cmd-params-cm
      data:
        server.insecure: "true"

  # Ajoute le sidecar CMP SOPS + le volume de la clé age sur le repo-server
  - target:
      kind: Deployment
      name: argocd-repo-server
    path: patches/repo-server-sops-sidecar.yaml
