apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-stack

resources:
  - 00-namespace.yaml
  - 01-storage.yaml
  - 10-llama-server.yaml
  - 20-sd-server.yaml
  - 30-open-webui.yaml
  - 40-ingress.yaml

generators:
  - ksops-generator.yaml
