apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

resources:
  - 00-namespace.yaml
  - 10-home-assistant.yaml
  - 40-ingress.yaml

generators:
  - ksops-generator.yaml
