apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openclaw

resources:
  - 00-namespace.yaml
  - 01-storage.yaml
  - 10-openclaw.yaml
  - 20-ingress.yaml

generators:
  - ksops-generator.yaml
